
version: "3.9"
services:
  api:
    build: .
    container_name: qna-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: qna-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
